```mermaid
flowchart TD
    vaults_kv_hub_lz_pro_spc1_01["vaults\nvaults_kv_hub_lz_pro_spc1_01"]
    publicIPAddresses_pip_hub_lz_pro_spc1_apg_01["publicIPAddresses\npublicIPAddresses_pip_hub_lz_pro_spc1_ap"]
    publicIPAddresses_pip_hub_lz_pro_spc1_bas_01["publicIPAddresses\npublicIPAddresses_pip_hub_lz_pro_spc1_ba"]
    publicIPAddresses_pip_hub_lz_pro_spc1_forti_01["publicIPAddresses\npublicIPAddresses_pip_hub_lz_pro_spc1_fo"]
    vaults_kv_hub_lz_pro_spc1_01_name["privateEndpointConnections\nvaults_kv_hub_lz_pro_spc1_01_name"]
    vaults_kv_hub_lz_pro_spc1_01_name["secrets\nvaults_kv_hub_lz_pro_spc1_01_name"]
    vaults_kv_hub_lz_pro_spc1_01_name["secrets\nvaults_kv_hub_lz_pro_spc1_01_name"]
    vaults_kv_hub_lz_pro_spc1_01_name["secrets\nvaults_kv_hub_lz_pro_spc1_01_name"]
    vaults_kv_hub_lz_pro_spc1_01_name["secrets\nvaults_kv_hub_lz_pro_spc1_01_name"]
    vaults_kv_hub_lz_pro_spc1_01_name["secrets\nvaults_kv_hub_lz_pro_spc1_01_name"]
    privateEndpoints_pe_kv_hub_lz_pro_spc1_01_name["privateDnsZoneGroups\nprivateEndpoints_pe_kv_hub_lz_pro_spc1_0"]
    virtualNetworks_vnet_hub_lz_pro_spc1_con_01["virtualNetworks\nvirtualNetworks_vnet_hub_lz_pro_spc1_con"]
    virtualNetworks_vnet_hub_lz_pro_spc1_con_01_name["subnets\nvirtualNetworks_vnet_hub_lz_pro_spc1_con"]
    virtualNetworks_vnet_hub_lz_pro_spc1_con_01_name["subnets\nvirtualNetworks_vnet_hub_lz_pro_spc1_con"]
    virtualNetworks_vnet_hub_lz_pro_spc1_con_01_name["subnets\nvirtualNetworks_vnet_hub_lz_pro_spc1_con"]
    virtualNetworks_vnet_hub_lz_pro_spc1_con_01_name["subnets\nvirtualNetworks_vnet_hub_lz_pro_spc1_con"]
    virtualNetworks_vnet_hub_lz_pro_spc1_con_01_name["subnets\nvirtualNetworks_vnet_hub_lz_pro_spc1_con"]
    virtualNetworks_vnet_hub_lz_pro_spc1_con_01_name["subnets\nvirtualNetworks_vnet_hub_lz_pro_spc1_con"]
    virtualNetworks_vnet_hub_lz_pro_spc1_con_01_name["subnets\nvirtualNetworks_vnet_hub_lz_pro_spc1_con"]
    applicationGateways_apg_hub_lz_pro_spc1_net_01["applicationGateways\napplicationGateways_apg_hub_lz_pro_spc1_"]
    privateEndpoints_pe_kv_hub_lz_pro_spc1_01["privateEndpoints\nprivateEndpoints_pe_kv_hub_lz_pro_spc1_0"]
    virtualNetworks_vnet_hub_lz_pro_spc1_con_01_name["subnets\nvirtualNetworks_vnet_hub_lz_pro_spc1_con"]
```
